#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="registry"

check_container_initialized
check_service_initialized init

if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
    log_path=${LOG_PATH}
    log_file=${LOG_FILE}
else
    log_path="/dev/"
    log_path="stderr"
fi

liftoff

print_info "Starting Docker registry ${DOCKER_REGISTRY_VERSION}"
exec registry serve /etc/docker/registry/config.yml 2>&1 >>${log_path}${log_file}
